# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.Measure',
                                    verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='количество'),
        ),
    ]
