# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 22:50
from __future__ import unicode_literals

import TonerProject.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='наименование категории товара', max_length=30, verbose_name='категория товара')),
                ('path', models.CharField(help_text='категории товара в адресной строке в латинских символах', max_length=30, validators=[TonerProject.validators.validator_path], verbose_name='наименование для адресной строки')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Category', verbose_name='Родительскиая категория')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': 'категория товара',
                'verbose_name_plural': 'категории товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='уникальный код товара служащий идентификатором товара в системе', max_length=10, unique=True, verbose_name='код товара')),
                ('code_ean13', models.CharField(default=None, max_length=13, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='штрих код EAN-13')),
            ],
            options={
                'verbose_name': 'код товара',
                'verbose_name_plural': 'коды товаров',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='наименование страны')),
            ],
            options={
                'db_table': 'country',
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='введите курс валюты используйте запятую для разделения целой и дробной части', verbose_name='курс')),
                ('date', models.DateField(default='01.01.1980', verbose_name='дата изменения курса')),
            ],
            options={
                'db_table': 'course',
                'verbose_name': 'курс валюты',
                'verbose_name_plural': 'курсы валют',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название валюты')),
                ('name_4217', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='допустимы только латинские буквы.')], verbose_name='название валюты alfa-3 ISO 4217')),
                ('code_4217', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='допустимы только цифровые символы.')], verbose_name='код валюты number-3 ISO 4217')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_course', to='system.Course', verbose_name='текущий курс')),
            ],
            options={
                'db_table': 'currency',
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='производитель товара')),
                ('site', models.CharField(default=None, max_length=30, null=True, unique=True, verbose_name='web сайт компании')),
            ],
            options={
                'db_table': 'developer',
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='характеристика товара', max_length=70, unique=True, verbose_name='характеристика')),
            ],
            options={
                'db_table': 'feature',
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характиристики',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="описание характеристик товара, может иметь количественное или булево значение 'есть/нет'", max_length=70, verbose_name='Модель или количество')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Feature', verbose_name='наименование характеристики')),
            ],
            options={
                'db_table': 'features',
                'verbose_name': 'характиристика товара',
                'verbose_name_plural': 'характиристики товаров',
                'ordering': ('group',),
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Шт', 'Штук'), ('Кг', 'Киллограммов'), ('Л', 'Литров')], default='Шт', max_length=20, unique=True, verbose_name='наименование единицы')),
                ('OKEI', models.CharField(max_length=3, verbose_name='код в Российской классификации единиц измерения')),
            ],
            options={
                'db_table': 'measure',
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='наименование продукта', max_length=30, verbose_name='наименование продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Category', verbose_name='категория продукта')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Code', verbose_name='коды продукта:')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer', verbose_name='производитель продукта')),
                ('features', models.ManyToManyField(blank=True, related_name='features', to='system.Features', verbose_name='характеристики продукта')),
                ('fifth_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fifth_features_view', to='system.Features', verbose_name='пятая характеристика')),
                ('first_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_features_view', to='system.Features', verbose_name='первая характеристика')),
                ('fourth_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_features_view', to='system.Features', verbose_name='четвертая характеристика')),
                ('include', models.ManyToManyField(blank=True, default=None, related_name='_product_include_+', to='system.Product', verbose_name='подходит для:')),
                ('second_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_features_view', to='system.Features', verbose_name='вторая характеристика')),
                ('sixth_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixth_features_view', to='system.Features', verbose_name='шестая характеристика')),
                ('third_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_features_view', to='system.Features', verbose_name='третья характеристика')),
            ],
            options={
                'db_table': 'product',
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='наименование группы характеристики товара', max_length=40, verbose_name='группа характеристики')),
                ('belongs', models.ManyToManyField(to='system.Category', verbose_name='принадлежность к категории товаров')),
            ],
            options={
                'db_table': 'type_of_feature',
                'verbose_name': 'группа характеристик',
                'verbose_name_plural': 'группы характеристик',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='features',
            name='group',
            field=models.ForeignKey(help_text='группа принадлежности характеристики', on_delete=django.db.models.deletion.CASCADE, to='system.Type', verbose_name='группа характеристик товара'),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_name', to='system.Currency', verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='course',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_relation', to='system.Currency', verbose_name='в валюте'),
        ),
    ]
