# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 21:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Бренд')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель картриджа')),
                ('weight', models.IntegerField(verbose_name='Вес(грамм)')),
            ],
            options={
                'db_table': 'cartridge',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Производитель')),
            ],
            options={
                'db_table': 'developer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number',
                 models.CharField(help_text='Пожалуйста используйте следующий формат: AA-xxxxxxx', max_length=10,
                                  validators=[system.models.validator_numerator], verbose_name='Номер заказа')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('comments', models.TextField(blank=True, max_length=100, verbose_name='Комментарий')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cartridge',
                                                verbose_name='Картридж')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель принтера')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Cartridge',
                                                verbose_name='Тип используемого картриджа')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer',
                                                verbose_name='Производитель оборудования')),
            ],
            options={
                'db_table': 'printer',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус заказа')),
                ('color', models.CharField(default='ffffff', max_length=6, validators=[
                    django.core.validators.RegexValidator('^[0-9a-fA-F]*$',
                                                          message='Цвет пиктограммы указывается в шестнадцатиричной системе.')],
                                           verbose_name='Цвет пиктограммы')),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тонер')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Brand',
                                            verbose_name='Марка тонера')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer',
                                                verbose_name='Производитель тонера')),
            ],
            options={
                'db_table': 'toner',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Status',
                                    verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='toner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Toner',
                                    verbose_name='Тип тонера'),
        ),
    ]
