# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0002_repairpart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджи'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Изготовитель', 'verbose_name_plural': 'Изготовители'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Печатающее устройство', 'verbose_name_plural': 'Печатающие устройства'},
        ),
        migrations.AlterModelOptions(
            name='repairpart',
            options={'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='toner',
            options={'verbose_name': 'Тонер', 'verbose_name_plural': 'Тонеры'},
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Изготовитель'),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='ffffff', max_length=6, validators=[
                django.core.validators.RegexValidator('^[0-9a-fA-F]*$',
                                                      message='Должен указывается в шестнадцатиричной системе.')],
                                   verbose_name='Цвет пиктограммы'),
        ),
    ]
