# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0003_auto_20160706_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Бренд это промышленый стандарт или тип производимого товара',
                                   max_length=20, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Производитель'),
        ),
    ]
