# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0004_auto_20160710_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование категории товара', max_length=30,
                                          verbose_name='Категория товара')),
            ],
            options={
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'category',
                'verbose_name': 'Категория товара',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код товара служащий идентификатором товара в системе',
                                          max_length=20, unique=True, verbose_name='Код товара')),
            ],
            options={
                'verbose_name_plural': 'Коды товаров',
                'verbose_name': 'Код товара',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Особенность товара', max_length=20, verbose_name='Особенность')),
            ],
            options={
                'verbose_name_plural': 'Особенности',
                'db_table': 'feature',
                'verbose_name': 'Особенность',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование товара', max_length=30, verbose_name='Товар')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Category',
                                               verbose_name='Категория товара')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Code')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'db_table': 'item',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(help_text='Тип особенности товара', max_length=40, verbose_name='Тип особенности')),
            ],
            options={
                'verbose_name_plural': 'Типы особенностей',
                'db_table': 'type_of_feature',
                'verbose_name': 'Тип особенности',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Вид работы')),
            ],
            options={
                'verbose_name_plural': 'Вид работ',
                'db_table': 'work',
                'verbose_name': 'Вид работы',
            },
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='toner',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='cartridge',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='developer',
        ),
        migrations.DeleteModel(
            name='RepairPart',
        ),
        migrations.RemoveField(
            model_name='toner',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='toner',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cartridge',
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Производитель товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Cartridge',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='Toner',
        ),
        migrations.AddField(
            model_name='item',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer',
                                    verbose_name='Производитель товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(to='system.Feature', verbose_name='Особенности товара'),
        ),
        migrations.AddField(
            model_name='item',
            name='include',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Item'),
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Type',
                                    verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Item',
                                    verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='order',
            name='work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Work',
                                    verbose_name='Вид работ'),
        ),
    ]
