# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0005_auto_20161207_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(help_text='Описание особенности товара', max_length=70, verbose_name='Описание')),
            ],
            options={
                'db_table': 'features',
                'verbose_name_plural': 'Группы особенностей',
                'verbose_name': 'Группа особенностей',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Группа особенности товара', max_length=70,
                                          verbose_name='Группа особенности товара')),
            ],
            options={
                'db_table': 'group',
                'verbose_name_plural': 'Группы',
                'verbose_name': 'Группа',
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='type',
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='Особенность товара', max_length=70, verbose_name='Особенность'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(to='system.Features', verbose_name='Особенности товара'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='include',
        ),
        migrations.AddField(
            model_name='item',
            name='include',
            field=models.ManyToManyField(default=None, to='system.Item', verbose_name='Подходит для...'),
        ),
        migrations.AddField(
            model_name='features',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Feature',
                                    verbose_name='Особенность'),
        ),
        migrations.AddField(
            model_name='features',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Group',
                                    verbose_name='Группа особенностей'),
        ),
    ]
