# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0006_auto_20161210_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Особенность', 'verbose_name_plural': 'Особенности'},
        ),
        migrations.AlterField(
            model_name='features',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Type',
                                    verbose_name='Группа особенностей'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
