# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0008_type_belongs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характиристики'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Характиристика товара', 'verbose_name_plural': 'Характиристики товара'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Группа характеристик', 'verbose_name_plural': 'Группы характеристик'},
        ),
        migrations.AddField(
            model_name='code',
            name='code_ean13',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=13, verbose_name='Штрих код EAN-13'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(help_text='Уникальный код товара служащий идентификатором товара в системе',
                                   max_length=10, unique=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='Характеристика товара', max_length=70, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Feature',
                                    verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='features',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Type',
                                    verbose_name='Характиристики товара'),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(help_text='Описание характеристик товара', max_length=70, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(to='system.Features', verbose_name='Характеристики товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='include',
            field=models.ManyToManyField(default=None, to='system.Item', verbose_name='Подходит для:'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Наименование группы характеристики товара', max_length=40,
                                   verbose_name='Группа характеристики'),
        ),
    ]
