# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 22:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0009_auto_20161218_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_ean13',
            field=models.CharField(default=None, max_length=13, validators=[
                django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')],
                                   verbose_name='Штрих код EAN-13'),
        ),
    ]
