# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 21:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0010_auto_20161218_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование продукта', max_length=30,
                                          verbose_name='Наименование продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Category',
                                               verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукт',
                'db_table': 'product',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='features',
        ),
        migrations.RemoveField(
            model_name='item',
            name='include',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default='00000000000', max_length=30, verbose_name='Серийный номер продукта'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_ean13',
            field=models.CharField(default=None, max_length=13, validators=[
                django.core.validators.RegexValidator('^[0-9]*$', message='Допустимы только цифровые символы.')],
                                   verbose_name='Штрих код EAN-13'),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Feature',
                                    verbose_name='Наименование характеристики:'),
        ),
        migrations.AlterField(
            model_name='features',
            name='group',
            field=models.ForeignKey(help_text='Группа принадлежности характеристики',
                                    on_delete=django.db.models.deletion.CASCADE, to='system.Type',
                                    verbose_name='Группа характеристик товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='system.Code', verbose_name='Коды продукта:'),
        ),
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer',
                                    verbose_name='Производитель продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='system.Features', verbose_name='Характеристики продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='include',
            field=models.ManyToManyField(blank=True, default=None, related_name='_product_include_+',
                                         to='system.Product', verbose_name='Подходит для:'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Product',
                                    verbose_name='Продукт'),
        ),
    ]
