# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 00:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import TonerProject.validators


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0012_auto_20161224_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория товара', 'verbose_name_plural': 'категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'код товара', 'verbose_name_plural': 'коды товаров'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'страна', 'verbose_name_plural': 'страны'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'производитель', 'verbose_name_plural': 'производители'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'характеристика', 'verbose_name_plural': 'характиристики'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'характиристика товара', 'verbose_name_plural': 'характиристики товара'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукт'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'статус', 'verbose_name_plural': 'статусы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'группа характеристик', 'verbose_name_plural': 'группы характеристик'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'вид работы', 'verbose_name_plural': 'вид работ'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='system.Category', verbose_name='Родительскиая категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='наименование категории товара', max_length=30,
                                   verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(help_text='уникальный код товара служащий идентификатором товара в системе',
                                   max_length=10, unique=True, verbose_name='код товара'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_ean13',
            field=models.CharField(default=None, max_length=13, validators=[
                django.core.validators.RegexValidator('^[0-9]*$', message='Допустимы только цифровые символы.')],
                                   verbose_name='штрих код EAN-13'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, verbose_name='наименование страны'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=20, verbose_name='производитель товара'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='характеристика товара', max_length=70, unique=True,
                                   verbose_name='характеристика'),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Feature',
                                    verbose_name='наименование характеристики:'),
        ),
        migrations.AlterField(
            model_name='features',
            name='group',
            field=models.ForeignKey(help_text='группа принадлежности характеристики',
                                    on_delete=django.db.models.deletion.CASCADE, to='system.Type',
                                    verbose_name='группа характеристик товара'),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(help_text='описание характеристик товара', max_length=70, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Country',
                                    verbose_name='страна производитель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Product',
                                    verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default='00000000000', max_length=30, verbose_name='серийный номер продукта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=100, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Item',
                                    verbose_name='устройство'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='пожалуйста используйте следующий формат: AA-xxxxxxx', max_length=10,
                                   validators=[
                                       TonerProject.validators.validator_numerator], verbose_name='номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Status',
                                    verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Work',
                                    verbose_name='вид работ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Category',
                                    verbose_name='категория продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='system.Code', verbose_name='коды продукта:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Developer',
                                    verbose_name='производитель продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='system.Features', verbose_name='характеристики продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='include',
            field=models.ManyToManyField(blank=True, default=None, related_name='_product_include_+',
                                         to='system.Product', verbose_name='подходит для:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='наименование продукта', max_length=30,
                                   verbose_name='наименование продукта'),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='ffffff', max_length=6, validators=[
                django.core.validators.RegexValidator('^[0-9a-fA-F]*$',
                                                      message='Должен указывается в шестнадцатиричной системе.')],
                                   verbose_name='цвет пиктограммы'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=20, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='type',
            name='belongs',
            field=models.ManyToManyField(to='system.Category', verbose_name='принадлежность к категории товаров:'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='наименование группы характеристики товара', max_length=40,
                                   verbose_name='группа характеристики'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=30, verbose_name='вид работы'),
        ),
    ]
