# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 22:39
from __future__ import unicode_literals

from django.db import migrations, models

import TonerProject.validators


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0013_auto_20161224_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='site',
            field=models.CharField(default=None, max_length=30, null=True, unique=True,
                                   verbose_name='web сайт компании'),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty',
            field=models.IntegerField(default=6, validators=[TonerProject.validators.validator_warranty],
                                      verbose_name='гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(
                help_text="описание характеристик товара, может иметь количественное или булево значение 'есть/нет'",
                max_length=70, verbose_name='Модель или количество'),
        ),
    ]
