# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('business', '0002_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='номер накладной')),
                ('date', models.DateField(verbose_name='дата документа')),
                ('delete', models.BooleanField(default=True, verbose_name='Черновик/Подлежит удалению')),
                ('enable', models.BooleanField(default=False, verbose_name='действующий документ')),
                ('created', models.DateTimeField(verbose_name='время/дата создания документа')),
                ('modified', models.DateTimeField(verbose_name='время/дата изменения документа')),
            ],
            options={
                'db_table': 'consignment',
                'verbose_name': 'реализация',
                'verbose_name_plural': 'реализации',
            },
        ),
        migrations.CreateModel(
            name='ConsignmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='номер в накладной')),
                ('quantity', models.FloatField(verbose_name='количество')),
                ('consignment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Consignment',
                                   verbose_name='накладная')),
                ('cost', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='business.Cost', verbose_name='стоимость единицы продукта без налогов')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Product',
                                           verbose_name='продукт')),
                ('tax', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                          to='business.Tax', verbose_name='налоговая ставка')),
            ],
            options={
                'db_table': 'consignment_items',
                'verbose_name': 'Продукция в накладной',
                'verbose_name_plural': 'Продукция в накладной',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='номер контракта')),
                ('date_begin', models.DateField(default='01.01.1980', verbose_name='дата заключения контракта')),
                ('date_expire', models.DateField(default='31.12.9999', verbose_name='дата истечения контракта')),
                ('delete', models.BooleanField(default=True, verbose_name='Черновик/Подлежит удалению')),
                ('enable', models.BooleanField(default=False, verbose_name='действующий документ')),
                ('created', models.DateTimeField(verbose_name='время/дата создания документа')),
                ('modified', models.DateTimeField(verbose_name='время/дата изменения документа')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_buyer',
                                            to='contractor.Contractor', verbose_name='покупатель')),
                ('creator',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_creator',
                                   to=settings.AUTH_USER_MODEL, verbose_name='автор документа')),
                ('modificator',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_modificator',
                                   to=settings.AUTH_USER_MODEL, verbose_name='изменил документ')),
                ('seller',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_seller',
                                   to='contractor.Contractor', verbose_name='продавец')),
            ],
            options={
                'db_table': 'contract',
                'verbose_name': 'контракт',
                'verbose_name_plural': 'контракты',
            },
        ),
        migrations.AddField(
            model_name='consignment',
            name='contract',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='consignment_contract', to='document.Contract',
                                    verbose_name='контракт'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_creator',
                                    to=settings.AUTH_USER_MODEL, verbose_name='автор документа'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='emitter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='consignment_emitter', to='contractor.Contractor',
                                    verbose_name='организация отпускающая груз'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='items',
            field=models.ManyToManyField(related_name='consignment_items', through='document.ConsignmentTable',
                                         to='system.Product', verbose_name='перемещаемый товар'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='modificator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_modificator',
                                    to=settings.AUTH_USER_MODEL, verbose_name='изменил документ'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='consignment_receiver', to='contractor.Contractor',
                                    verbose_name='организация принимающая груз'),
        ),
    ]
