# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignmenttable',
            options={'verbose_name': 'продукт в накладной', 'verbose_name_plural': 'продукты в накладной'},
        ),
        migrations.AddField(
            model_name='consignmenttable',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.Measure',
                                    verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='consignmenttable',
            name='cost',
            field=models.FloatField(default=0.0, null=True, verbose_name='стоимость единицы продукта без налогов'),
        ),
    ]
