# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0003_consignmenttable_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmenttable',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='system.Country', verbose_name='страна происхождения'),
        ),
    ]
