# Generated by Django 2.0.1 on 2018-02-12 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20170828_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='тип документа')),
                ('type', models.CharField(max_length=30, verbose_name='тип документа в системе')),
            ],
            options={
                'verbose_name': 'тип документа',
                'verbose_name_plural': 'типы документов',
                'db_table': 'document_type',
            },
        ),
        migrations.AlterField(
            model_name='consignmenttable',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='количество'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consignment_items', to='document.DocType', verbose_name='перемещаемый товар'),
            preserve_default=False,
        ),
    ]
