# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 22:53
from __future__ import unicode_literals

import TonerProject.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('system', '0018_auto_20170102_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number',
                 models.CharField(default='0000000000', max_length=30, verbose_name='серийный номер продукта')),
                ('warranty', models.IntegerField(default=6, validators=[TonerProject.validators.validator_warranty],
                                                 verbose_name='гарантийный срок')),
                ('country',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Country',
                                   verbose_name='страна производитель')),
            ],
            options={
                'db_table': 'item',
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='название типа поставки')),
            ],
            options={
                'db_table': 'package',
                'verbose_name': 'тип поставки',
                'verbose_name_plural': 'типов поставок',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.Package',
                                    verbose_name='тип поставки'),
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='system.Product',
                                    verbose_name='продукт'),
        ),
    ]
