# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trade', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='ffffff', max_length=6, validators=[
                django.core.validators.RegexValidator('^[0-9a-fA-F]*$',
                                                      message='должен указывается в шестнадцатиричной системе.')],
                                   verbose_name='цвет пиктограммы'),
        ),
    ]
