# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', message='Только буквенноцифровые символы допустимы.')], verbose_name='Логин')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия пользователя')),
                ('tagline', models.CharField(blank=True, max_length=140, null=True, verbose_name='Статус')),
                ('user_photo', models.FilePathField(blank=True, default='profile/defaultprofileimage.jpg', null=True, verbose_name='Аватар')),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Укажите правильный номер телефона', regex='^\\d{10}$')])),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'db_table': 'account',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('account', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')])),
                ('bik', models.CharField(db_index=True, max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')])),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование компании')),
                ('boss_first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('boss_second_name', models.CharField(blank=True, max_length=40, null=True)),
                ('boss_last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('inn', models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')])),
                ('ogrn', models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')])),
                ('okpo', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')])),
                ('okato', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')])),
                ('address', models.CharField(max_length=100, null=True)),
                ('bankaccount', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Только цифровые символы допустимы.')])),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Bank')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Company', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
