# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-13 23:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0005_auto_20151113_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updated_at',
            new_name='date_updated',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True, validators=[
                django.core.validators.RegexValidator('^[0-9a-zA-Z]*$',
                                                      message='Only alphanumeric characters are allowed.')]),
        ),
    ]
