# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-13 21:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0006_auto_20151114_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_photo',
            field=models.FileField(default='/profile/defaultprofileimage.jpg', upload_to='/profile/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True, validators=[
                django.core.validators.RegexValidator('^[0-9a-zA-Z]*$',
                                                      message='Только буквенноцифровые символы допустимы.')]),
        ),
    ]
