# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 22:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1, verbose_name='стоимость')),
                ('date', models.DateField(default='01.01.1980', verbose_name='дата установки цены')),
                ('time', models.TimeField(verbose_name='время установки цены')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Currency',
                                               verbose_name='валюта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Product',
                                              verbose_name='товар')),
            ],
            options={
                'db_table': 'cost',
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='статус заказа')),
                ('color', models.CharField(default='ffffff', max_length=6, validators=[
                    django.core.validators.RegexValidator('^[0-9a-fA-F]*$',
                                                          message='должен указывается в шестнадцатиричной системе.')],
                                           verbose_name='цвет пиктограммы')),
            ],
            options={
                'db_table': 'trade_status',
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'статусы заказов',
            },
        ),
    ]
