# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='без налога', max_length=30, verbose_name='вид налога')),
                ('value', models.FloatField(default=0, verbose_name='налоговая ставка')),
            ],
            options={
                'db_table': 'tax',
                'verbose_name_plural': 'налогов',
                'verbose_name': 'налог',
            },
        ),
    ]
