# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0001_initial'),
        ('business', '0003_remove_cost_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='currency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='system.Currency',
                                    verbose_name='валюта'),
            preserve_default=False,
        ),
    ]
